el_mirador = Site.create(name: "el Mirador", description: "El Mirador flourished from about the 6th century BCE to the 1st century CE, reaching its height from the 3rd century BCE. Then it experienced a hiatus of construction and perhaps abandonment for generations,[5] followed by re-occupation and further construction in the Late Classic era, and a final abandonment about the end of the 9th century. The civic center of the site covers some 10 square miles (26 km2) with several thousand structures, including monumental architecture from 10 to 72 meters high.
One of the key elements for this tremendous rise in human population was the many bajos, seasonal swamps, in the region. Tropical-forest soil contains hardly any nutrients and most of the nutrients present get washed away by rain. Yet the Maya developed a system that was highly productive. In the Mirador basin, the swamps provided the solution. By importing mud from the swamps by the thousands of tonnes, the Maya created mud-covered terraces ready for agriculture. By adding lime to the soil, they elevated the pH, making it suitable for a variety of crops: corn, squash, beans, cacao, cotton and palm. When the ground was depleted of nutrients, adding another layer of mud reinvigorates the fields.[6]
There is a number of triadic structures (around 35 structures),[7] consisting of large artificial platforms topped with a set of 3 summit pyramids. The most notable of such structures are three huge complexes; one is nicknamed El Tigre, with height 55 metres (180 ft); the other is called La Danta (or Danta) temple. The La Danta temple measures approximately 72 metres (236 ft) tall from the forest floor,[8] and considering its total volume (2,800,000 cubic meters) is one of the largest pyramids in the world.[9] When the large man-made platform that the temple is built upon (some 180,000 square meters) is included in calculations, La Danta is considered by some archeologists to be one of the most massive ancient structures in the world.[10] Also the Los Monos complex is very large (48 meters high) although not as well known. Most of the structures were originally faced with cut stone which was then decorated with large stucco masks depicting the deities of Maya mythology. According to Carlos Morales-Aguilar, a Guatemalan archaeologist from Pantheon-Sorbonne University, the city appears to have been planned from its foundation, as extraordinary alignments have been found between the architectural groups and main temples, which were possibly related to solar alignments.[11] The study reflects an importance of urban planning and sacred spaces since the first settlers.")

machu_picchu = Site.create(name: "Machu Picchu", description: "permanently. Though the estate belonged to Pachacutec, religious specialists and temporary specialized workers (mayocs) lived there as well, most likely for the rulers well-being and enjoyment. During the harsher season, staff dropped down to around a hundred servants and a few religious specialists focused on maintenance alone.[21]
Studies show that according to their skeletal remains, most people who lived there were immigrants from diverse backgrounds. They lacked the chemical markers and osteological markers they would have if they had been living there their whole lives. Instead, there was bone damage from various species of water parasites indigenous to different areas of Peru. There were also varying osteological stressors and varying chemical densities suggesting varying long-term diets characteristic of specific regions that were spaced apart.[26] These diets are composed of varying levels of maize, potatoes, grains, legumes, and fish, but the overall most recent short-term diet for these people was composed of less fish and more corn. This suggests that several of the immigrants were from more coastal areas and moved to Machu Picchu where corn was a larger portion of food intake.[25] The skeletal remains found at Machu Picchu are also unique in their level of natural bone damage from laborious activities. Most people found at the site had lower levels of arthritis and bone fractures than those found in most sites of the Inca Empire. Inca individuals who had arthritis and bone fractures were typically those who performed heavy physical labor (such as the Mita) and/or served in the Inca military.[21]
Llama with Machu Picchu ruins in the background.
Animals are also suspected to have immigrated to Machu Picchu as there were several bones found that were not native to the area. Most animal bones found were from llamas and alpacas. These animals naturally live at altitudes of 4,000 metres (13,000 ft) rather than the 2,400 metres (7,900 ft) elevation of Machu Picchu. Most likely, these animals were brought in from the Puna region[27] for meat consumption and for their pelts. Guinea pigs were also found at the site in special burial caves, suggesting that they were at least used for funerary rituals,[21] as it was common throughout the Inca Empire to use them for sacrifices and meat.[28] Six dogs were also recovered from the site. Due to their placements among the human remains, it is believed that they served as companions of the dead.[21]")

great_pyramid_of_giza = Site.create(name: "Great Pyramid of Giza", description: "Egyptologists believe the pyramid was built as a tomb for the Fourth Dynasty Egyptian pharaoh Khufu (often Hellenized as Cheops) and was constructed over a 20-year period. Khufus vizier, Hemiunu (also called Hemon), is believed by some to be the architect of the Great Pyramid.[2] It is thought that, at construction, the Great Pyramid was originally 280 Egyptian Royal cubits tall (146.5 metres (480.6 ft)), but with erosion and the absence of its pyramidion, its present height is 138.8 metres (455.4 ft). Each base side was 440 cubits, 230.4 metres (755.9 ft) long. The mass of the pyramid is estimated at 5.9 million tonnes. The volume, including an internal hillock, is roughly 2,500,000 cubic metres (88,000,000 cu ft).[3]
The first precision measurements of the pyramid were made by Egyptologist Sir Flinders Petrie in 1880–82 and published as The Pyramids and Temples of Gizeh.[4] Almost all reports are based on his measurements. Many of the casing-stones and inner chamber blocks of the Great Pyramid fit together with extremely high precision. Based on measurements taken on the north-eastern casing stones, the mean opening of the joints is only 0.5 millimetres (0.020 in) wide.[5]
The pyramid remained the tallest man-made structure in the world for over 3,800 years,[6] unsurpassed until the 160-metre-tall (520 ft) spire of Lincoln Cathedral was completed c. 1300. The accuracy of the pyramids workmanship is such that the four sides of the base have an average error of only 58 millimetres in length.[7] The base is horizontal and flat to within ±15 mm (0.6 in).[8] The sides of the square base are closely aligned to the four cardinal compass points (within four minutes of arc)[9] based on true north, not magnetic north,[10] and the finished base was squared to a mean corner error of only 12 seconds of arc.[11]
The completed design dimensions, as suggested by Petries survey and subsequent studies, are estimated to have originally been 280 Egyptian Royal cubits high by 440 cubits long at each of the four sides of its base. The ratio of the perimeter to height of 1760/280 Egyptian Royal cubits equates to 2π to an accuracy of better than 0.05 percent (corresponding to the well-known approximation of π as 22/7). Some Egyptologists consider this to have been the result of deliberate design proportion. Verner wrote, We can conclude that although the ancient Egyptians could not precisely define the value of π, in practice they used it.[12] Petrie concluded: but these relations of areas and of circular ratio are so systematic that we should grant that they were in the builders design.[13] Others have argued that the ancient Egyptians had no concept of pi and would not have thought to encode it in their monuments. They believe that the observed pyramid slope may be based on a simple seked slope choice alone, with no regard to the overall size and proportions of the finished building.[14] In 2013, rolls of papyrus called the Diary of Merer were discovered written by some of those who delivered limestone and other construction materials from Tora to Giza.")

mark = User.create(name: "Mark")
sean = User.create(name: "Sean")
eva = User.create(name: "Eva")

comment1 = Comment.create(user_id: 0, site_id: 0, content: "There is a secret entence on the East side.", username: "Mark")
comment2 = Comment.create(user_id: 0, site_id: 1, content: "It usually rains there during the summer.", username: "Mark")

comment3 = Comment.create(user_id: 1, site_id: 1, content: "That place is scary af.", username: "Sean")
comment4 = Comment.create(user_id: 1, site_id: 2, content: "Does anyone know how to get there?", username: "Sean")

comment5 = Comment.create(user_id: 2, site_id: 0, content: "WOW!! OMG THAT LOOKS SO BEAUTIFUL!", username: "Eva")
comment6 = Comment.create(user_id: 2, site_id: 2, content: "OOOOOO I WANNA GO THERE!", username: "Eva")